### ISSUE TITLE
LocalSend fails to launch with terminal message "xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb"

### ISSUE THREAD

**Issue by thatLeaflet** [localsend/snap#3]
This is an upstream snap issue, tracked here: https://github.com/ubuntu/gnome-sdk/issues/232.

It is seemingly fixed, but the update seemingly has not been released yet.

This also seems to be Wayland only according to: https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/2073339

### Workarounds

Check for updates in App Center or from the terminal with `sudo snap refresh`. An update fixing the issue may be out by the time you read this.

You can also try to revert back to an older working version of the gnome 46 runtime by running `snap revert gnome-46-2404`. This may not work if you never previously installed the gnome 46 runtime.

If that doesn't work, the Xorg session should work.

**Comment by nteodosio** [comment]
Hi, the fix, which I confirmed in Chromium, should be soon enough in gnome-46-2404 stable channel, but it is already in candidate channel so an alternative is

    snap refresh --candidate gnome-46-2404

**Comment by thatLeaflet** [comment]
Fix was released in stable channel.
